---
title: "ggplot 1"
output: github_document
---

```{r, warning = FALSE, message = FALSE}
library(tidyverse)
library(ggridges)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
```


Loading Dataset that we will use often:

```{r, warning = FALSE}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```


## Scatterplots

```{r, warning = FALSE}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()
  
```

You can save ggplots as well:

```{r, warning = FALSE}
ggp_tmax_tmin =
  weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()
```


## Let's fancy it up!

```{r, warning = FALSE}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.3) +
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name)
```

One more scatterplot:

```{r,warning = FALSE}
weather_df %>%
  ggplot(aes(x = date, y = tmax, size = prcp)) +
  geom_point(alpha = .3) +
  facet_grid(. ~ name) +
  geom_smooth(se = FALSE)
```


## Use data manipulation as part of this

```{r, warning = FALSE}
weather_df %>%
  filter(name == "CentralPark_NY") %>%
  mutate(
    tmax = tmax * (9/5) + 32,
    tmin = tmin * (9/5) + 32
  ) %>%
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point() 
```


# Stacking geoms

```{r, warning = FALSE}
weather_df %>%
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_smooth()
```

## Fancy hexagon scatterplots

```{r, warning = FALSE}
ggplot(weather_df, aes(x = tmax, y = tmin)) + geom_hex()
```

# Histograms

```{r, warning = FALSE}
weather_df %>%
  ggplot(aes(x = tmax, fill = name)) + 
  geom_histogram()

```

# Boxplots

```{r, warning = FALSE}
weather_df %>%
  ggplot(aes(x = tmax, fill = name)) + 
  geom_boxplot()
```

# Violin Plots

```{r, warning = FALSE}
weather_df %>%
  ggplot(aes(x = name, y = tmax, fill = name)) + 
  geom_violin()
```

# Density Plots

```{r, warning = FALSE}
weather_df %>%
  ggplot(aes(x = tmax, y = name)) + 
  geom_density_ridges(alpha = 0.8, scale = 0.8)
```

## Embedded plots

```{r, warning = FALSE, fig.width = 12}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.3)
```



```{r}

```



```{r}

```



```{r}

```